import { CheckCircleIcon } from '@heroicons/react/solid';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Header from '../components/Header';

function success() {
    const router = useRouter()
    return (
        <div className='bg-gray-100 h-screen'>
            <Head>
                <title>Amazon - Success</title>

                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                {/* for post picture */}
                <meta property="og:title" content="" />
                <meta property="og:type" content="" />
                <meta property="og:image" content="/amazon_image.jpg" />
                <meta name="twitter:card" content="summary_large_image" />

                <meta property="og:description" content="" />
                <meta name="twitter:image:alt" content="" />
            </Head>
            <Header />

            <main className='max-w-screen-lg mx-auto'>
                <div className='flex flex-col p-10 bg-white'>
                    <div className='flex items-center space-x-2 mb-5'>
                        <CheckCircleIcon className='text-green-500 h-10' />

                        <h1 className='text-3xl'>Thank you, your order has been confirmed!</h1>
                    </div>
                    <p>Thank you for shopping with us, We'll send a confirmation once your item has shipped, if you would like to check status of your order(s) please press the link below. </p>

                    <button onClick={() => router.push('/orders')} className='button mt-8 '>Go to my Orders</button>
                </div>


            </main>
        </div>
    );
}

export default success;
